ExtraSliceV2/Controllers/CartaController.cs
using ApiProyectoExtraSlice.Models;
using ExtraSliceV2.Extensions;
using ExtraSliceV2.Filters;
using ExtraSliceV2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using MVCApiExtraSlice.Services;
using Newtonsoft.Json;

namespace ExtraSliceV2.Controllers
{
    public class CartaController : Controller
    {
        private ServiceRestaurante service;
        private ServiceCacheRedis serviceCache;
        private IMemoryCache memoryCache;

        public CartaController(ServiceRestaurante service, IMemoryCache memoryCache, ServiceCacheRedis serviceCache)
        {
            this.service = service;
            this.memoryCache = memoryCache;
            this.serviceCache = serviceCache;

        }


        #region CATEGORIA
        public async Task<IActionResult> Index()
        {
            List<Categoria> categorias = new();
            categorias = await this.service.GetAllCategoriasAsync();
            foreach (var cat in categorias)
            {
                if (cat.Imagen != null)
                {
                    cat.Imagen = await this.service.GetBlobUriAsync("extrasliceblobs", cat.Imagen);
                }
            }
            return View(categorias);
        }
        #endregion


        #region RESTAURANTE

        public async Task<IActionResult> _RestaurantesPartial()
        {
            List<Restaurante> restaurantes = new List<Restaurante>();
            restaurantes = await this.service.GetRestaurantesAsync();
            foreach (var res in restaurantes)
            {
                if (res.Imagen != null)
                {
                    res.Imagen = await this.service.GetBlobUriAsync("extrasliceblobs", res.Imagen);
                }
            }
            return PartialView("_RestaurantesPartial", restaurantes);
        }

        public async Task<IActionResult> _ResaturanteOnCategoria(int idcategoria)
        {

            List<Restaurante> restaurantes = new List<Restaurante>();
            restaurantes = await this.service.RestaurantesByCategoriaAsync(idcategoria); ;
            foreach (var res in restaurantes)
            {
                if (res.Imagen != null)
                {
                    res.Imagen = await this.service.GetBlobUriAsync("extrasliceblobs", res.Imagen);
                }
            }
            return PartialView("_ResaturanteOnCategoria", restaurantes);
        }

        public async Task<IActionResult> _RestaurantesByDinero(int dinero)
        {

            List<Restaurante> restaurantes = new List<Restaurante>();
            restaurantes = await this.service.RestaurantesByMoneyAsync(dinero);
            foreach (var res in restaurantes)
            {
                if (res.Imagen != null)
                {
                    res.Imagen = await this.service.GetBlobUriAsync("extrasliceblobs", res.Imagen);
                }
            }
            return PartialView("_ResaturanteOnCategoria", restaurantes);
        }

        public async Task<IActionResult> _RestauranteByName(string name)
        {
            List<Restaurante> restaurantes = await this.service.GetRestaurantesAsync();
            //var result = restaurantes.Where(r => r.Nombre_restaurante.Contains(name)).ToList();
            var result = restaurantes.Where(x => x.Nombre_restaurante.StartsWith(name, StringComparison.OrdinalIgnoreCase)).Select(x => x.Nombre_restaurante);
            return Json(result);
        }
        public async Task<IActionResult> _ShowRestauranteByName(string name)
        {
            Restaurante restaurante = await this.service.RestauranteByNameAsync(name);

            if (restaurante.Imagen != null)
            {
                restaurante.Imagen = await this.service.GetBlobUriAsync("extrasliceblobs", restaurante.Imagen);
            }

            return PartialView("_ShowRestauranteByName", restaurante);
        }

        public async Task<IActionResult> Restaurante(int idrestaurante)
        {

            RestauranteProductos restauranteProductos = new RestauranteProductos
            {
                Restaurante = await this.service.GetOneRestauranteAsync(idrestaurante),
                Productos = await this.service.FindProductosByRestauranIdAsync(idrestaurante)
            };

            if (restauranteProductos.Restaurante.Imagen != null)
            {
                restauranteProductos.Restaurante.Imagen = await this.service.GetBlobUriAsync("extrasliceblobs", restauranteProductos.Restaurante.Imagen);
            }

            return View(restauranteProductos);
        }
        #endregion

        
        #region CARRITO CACHE
        [AuthorizeUsuarios]
        public async Task<IActionResult> SeleccionarProducto(int idproducto, int idrestaurante)
        {
            //BUSCAMOS EL PRODUCTO 
            Producto producto = await this.service.FindProductoAsync(idproducto);
            //ALMACENAMOS EL PRODUCTO EN CACHE REDIS
            string token = HttpContext.Session.GetString("TOKEN");
            this.serviceCache.AddProductoCarrito(producto, token);
            return RedirectToAction("Restaurante", new { idrestaurante = idrestaurante });
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> CarritoProductos()
        {
            string token = HttpContext.Session.GetString("TOKEN");
            List<Producto> productosFavoritos = await this.serviceCache.GetProductosCarrito(token);
            if (productosFavoritos == null)
            {
                ViewData["mensaje"] = "No hay productos";
            }
            return View(productosFavoritos);
        }

        [HttpPost]
        [AuthorizeUsuarios]
        public async Task<IActionResult> CarritoProductos(List<int> idproducto, List<int> cantidad)
        {
            string token = HttpContext.Session.GetString("TOKEN");
            List<Producto> productosSession = await this.service.GetProductosFromSessionAsync(idproducto, token);
            string productostring = JsonConvert.SerializeObject(productosSession);

            List<int> prodCantidad = cantidad;
            string prodCanString = JsonConvert.SerializeObject(prodCantidad);

            Usuario usuario = await this.service.GetPerfilUserAsync(token);
            await this.service.SendMailAsync(usuario.Email, productostring, prodCanString);


            await this.service.FinalizarPedidoAsync(usuario.IdUser, idproducto, cantidad, token);
            this.serviceCache.DeleteAllCarrito(token);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteCarrito(int idproducto)
        {
            string token = HttpContext.Session.GetString("TOKEN");
            this.serviceCache.DeleteProductoCarrito(idproducto, token);
            return RedirectToAction("CarritoProductos");
        }

        #endregion


        #region FAVORITO CACHE
        [AuthorizeUsuarios]
        public async Task<IActionResult> SeleccionarFavorito(int idfavorito)
        {
            //BUSCAMOS EL PRODUCTO DENTRO DEL XML PARA RECUPERARLO
            Producto producto = await this.service.FindProductoAsync(idfavorito);
            //ALMACENAMOS EL PRODUCTO EN CACHE REDIS
            string token = HttpContext.Session.GetString("TOKEN");
            this.serviceCache.AddProductoFavorito(producto, token);
            ViewData["MENSAJE"] = "Producto almacenado en Favoritos";
            return RedirectToAction("Index");
        }
        [AuthorizeUsuarios]
        public async Task<IActionResult> Favoritos()
        {
            string token = HttpContext.Session.GetString("TOKEN");
            List<Producto> productosFavoritos = await this.serviceCache.GetProductosFavoritos(token);
            return View(productosFavoritos);
        }

        public async Task<IActionResult> DeleteFavorito(int idproducto)
        {
            string token = HttpContext.Session.GetString("TOKEN");
            this.serviceCache.DeleteProductoFavorito(idproducto, token);
            return RedirectToAction("Favoritos");
        }
        #endregion


        #region USER

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UsuarioAux usuario)
        {
            await this.service.RegisterUserAsync(usuario.Nombre_cliente, usuario.Direccion, usuario.Telefono, usuario.Email, usuario.Password);
            return RedirectToAction("Index");
        }

        //miedo
        [AuthorizeUsuarios]
        public async Task<IActionResult> PerfilUsuario()
        {
            string token = HttpContext.Session.GetString("TOKEN");
            Usuario user = await this.service.GetPerfilUserAsync(token);
            return View(user);
        }


        #endregion

    }
}

ExtraSliceV2/Views/Carta/CarritoProductos.cshtml
@using System.Security.Claims;
@model List<Producto>
@{
   

    decimal total = 0;
    @if (Model != null)
    {
        foreach (Producto pro in Model)
        {
            total += pro.Precio;
        }
    }

}

@if (Model != null)
{

    <div class="shopping-cart">
        <!-- Title -->
        <div class="title">
            Pedido
        </div>
        <form method="post">
            
            @foreach (Producto pro in Model)
            {
                <div class="item">
                    <div class="buttons">
                        <span class="delete-btn"></span>
                        <span class="like-btn"></span>
                    </div>
                    <div class="description">
                        <label>@pro.Nombre_producto</label>
                        <input class="form-control" type="hidden" name="idproducto" value="@pro.IdProducto">


                    </div>

                    <div class="description">
                        <label>@pro.Precio</label>
                        <input class="form-control" type="hidden" name="precio" value="@pro.Precio" />
                    </div>


                    <div class="quantity">
                        <button type="button" class="minus-btn" onclick="disminuirInput(@pro.IdProducto)" id="disminuir_@pro.IdProducto" value="@pro.Precio">-</button>
                        <input class="form-control" id="valor_@pro.IdProducto" name="cantidad" value="1" />
                        <button type="button" class="plus-btn" onclick="aumentarInput(@pro.IdProducto)" id="incrementar_@pro.IdProducto" value="@pro.Precio">+</button>
                    </div>
                    <a asp-controller="Carta" asp-action="DeleteCarrito" asp-route-idproducto="@pro.IdProducto" class="delete-btn"><img src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/remove.png" /></a>

                </div>
            }
            <h1 class="total-price" id="total">@total</h1>
            <button class="bot" type="submit">Realizar Pedido</button>
        </form>
    </div>
}
else
{
    <h1 style="text-align:center;font-family: Raleway;">@ViewData["mensaje"]</h1>
}

@section Scripts{
    <script>
        $(document).ready(function () {
            $('.like-btn').on('click', function () {
                $(this).toggleClass('is-active');
            });
        })

        var total = parseFloat("@total".replace(/,/g, "."));
        function aumentarInput(id) {
            var idBoton = event.target.id;
            var idInput = "valor_" + id;
            var valorPrecio = "incrementar_" + id;
            var input = document.getElementById(idInput);
            var precio = document.getElementById(valorPrecio).value;
            const idcaja = document.getElementById("total");

            if (input.value >= 5) {
                input.value = 5;
            } else {
                input.value++;
                total += parseFloat(precio.replace(/,/g, "."));
                console.log(total.toFixed(2));
                idcaja.innerText = total.toFixed(2);
            }


        }
        function disminuirInput(id) {
            var idBoton = event.target.id;
            var idInput = "valor_" + id;
            var valorPrecio = "disminuir_" + id;
            var input = document.getElementById(idInput);
            var precio = document.getElementById(valorPrecio).value;
            const idcaja = document.getElementById("total");

            if (input.value <= 0) {
                input.value = 0;
            } else {
                input.value--;
                total -= parseFloat(precio.replace(/,/g, "."));
                idcaja.innerText = total.toFixed(2);
            }


        }
    </script>
    }

ExtraSliceV2/Views/Carta/Favoritos.cshtml
@using Microsoft.Extensions.Caching.Memory;
@inject IMemoryCache memoryCache
@model List<Producto>


@if(Model != null)
{
    
<div class="shopping-cart">
    <!-- Title -->
    @foreach (Producto pro in Model)
    {
        <div class="item">
            <div class="buttons">
                <span class="delete-btn"></span>
                <span class="like-btn"></span>
            </div>
            <div class="description">
                <label>@pro.Nombre_producto</label>
                <input class="form-control" type="hidden" name="idproducto" value="@pro.IdProducto">


            </div>

            <div class="description">
                <label>@pro.Precio</label>
                <input class="form-control" type="hidden" name="precio" value="@pro.Precio" />
            </div>

                <a asp-controller="Carta" asp-action="DeleteFavorito" asp-route-idproducto="@pro.IdProducto" class="delete-btn"><img src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/remove.png" /></a>
        </div>
    }
   
   
</div>
}else{
    <h1 style="text-align:center;font-family: Raleway;">No hay Favoritos</h1>
}

ExtraSliceV2/Views/Carta/Index.cshtml
@model List<Categoria>

<div class="icon-container">
    @foreach (Categoria cat in Model)
    {
        <img src="@cat.Imagen" class="fa-arrow-up categ" data-id="@cat.IdCategoria" />

        <br />
    }
</div>
<div>
    <section class="carousel">
        <div class="carousel__container">



            <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="56" class="carousel--item">
                <img class="carousel--item__img"
                     src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/BurgerKing.jpg"
                     alt="item" />

                <div class="carousel--item__details">
                   @* <div>
                        <img src="../src/img/carousel--play.svg" alt="icon play" />
                        <img src="../src/img/carousel--plus.svg" alt="icon add" />
                    </div>

                    <p class="carousel--item__details--title">Titulo provisional</p>
                    <p class="carousel--item__details--subtitle">
                        2020 16+ 114 Minutos
                    </p>*@
                </div>
            </a>




            <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="55" class="carousel--item">
                <img class="carousel--item__img"
                     src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/Goiko-Princesa26.jpg"
                     alt="item" />

                <div class="carousel--item__details">
                    @*<div>
                        <img src="../src/img/carousel--play.svg" alt="icon play" />
                        <img src="../src/img/carousel--plus.svg" alt="icon add" />
                    </div>

                    <p class="carousel--item__details--title">Titulo provisional</p>
                    <p class="carousel--item__details--subtitle">
                        2020 16+ 114 Minutos
                    </p>*@
                </div>
            </a>



            <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="57" class="carousel--item">
                <img class="carousel--item__img"
                     src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/McDonalds.jpg"
                     alt="item" />

              <div class="carousel--item__details">
                    @*<div>
                        <img src="../src/img/carousel--play.svg" alt="icon play" />
                        <img src="../src/img/carousel--plus.svg" alt="icon add" />
                    </div>

                    <p class="carousel--item__details--title">Titulo provisional</p>
                    <p class="carousel--item__details--subtitle">
                        2020 16+ 114 Minutos
                    </p>*@
                </div>
            </a>


        </div>
</div>
<div class="filters">

    <div class="precios">

        <h1>Rango de precios</h1>
        <input type="range" id="range-input" min="3" max="30" step="1" value="0">
        <span id="range-value">0€</span>
    </div>

   

    <div class="search-container">
        <form>
            <input type="text" id="searchBar" placeholder="Buscar...">
            <button type="submit">Buscar</button>
        </form>
    </div>

</div>

<div class="restaurantes elemento" id="rest"></div>



@section Scripts {
    <script>

        const rangeInput = document.getElementById('range-input');
        const rangeValue = document.getElementById('range-value');

        rangeInput.addEventListener('input', (event) => {
            rangeValue.innerHTML = event.target.value + ""+"€";
        });

        $(document).ready(function () {

            var request = "/Carta/_RestaurantesPartial";
            $("#rest").load(request);


            $(".categ").click(function () {
                var idCategoria = $(this).data("id");
                console.log(idCategoria);
                var request = "/Carta/_ResaturanteOnCategoria?idcategoria=" + idCategoria;
                $("#rest").load(request);
            });

            $("#range-input").change(function () {
                var dinero = $(this).val();
                console.log(dinero);
                if (dinero <= 2) {
                    alert("No hay Restaurantes");
                    var request = "/Carta/_RestaurantesPartial";
                    $("#rest").load(request);

                }
                {
                    var request = "/Carta/_RestaurantesByDinero?dinero=" + dinero;
                    $("#rest").load(request);
                }

            });
            $(function () {
                $('#searchBar').autocomplete({
                    source: function (request, response) {
                        $.ajax({
                            url: '/Carta/_RestauranteByName',
                            data: { name: request.term },
                            success: function (data) {
                                response(data);
                            }
                        });
                    },
                    minLength: 1,
                    select: function (event, ui) {
                        // Do something when a result is selected
                        console.log(ui.item.value)
                        var request = "/Carta/_ShowRestauranteByName?name=" + encodeURIComponent(ui.item.value) ;
                        $("#rest").load(request);
                    }
                });
            });

        })
    </script>
}

ExtraSliceV2/Views/Carta/PerfilUsuario.cshtml
@model Usuario
@using System.Security.Claims;
@{
    //tring IdUser = Context.User.FindFirstValue(ClaimTypes.NameIdentifier);
}
@if(Model != null)
{
    <form class="form">
        <h2>Perfil de Usuario</h2>
        <div class="form-group">
            <label for="email">Nombre:</label>
            <div class="relative">
                <input class="form-control" id="name" type="text" autocomplete="" value="@Model.Nombre_cliente" placeholder="@Model.Nombre_cliente">
                <i class="fa fa-user"></i>
            </div>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <div class="relative">
                <input class="form-control" type="email" required="" value="@Model.Email" placeholder="@Model.Email">
                <i class="fa fa-envelope"></i>
            </div>
        </div>
        <div class="form-group">
            <label for="email">Teléfono:</label>
            <div class="relative">
                <input class="form-control" type="text" maxlength="10" value="@Model.Telefono" placeholder="@Model.Telefono">
                <i class="fa fa-phone"></i>
            </div>
        </div>
        <div class="form-group">
            <label for="email">Dirección:</label>
            <div class="relative">
                <input class="form-control" type="url" pattern="https?://.+" required="" value="@Model.Direccion" placeholder="@Model.Direccion">
                <i class="fa fa-building"></i>
            </div>
        </div>
    </form>
}

ExtraSliceV2/Views/Carta/Register.cshtml
<div class="login-container">
    <section class="login" id="login">
        <header>
            <h2>eXtraSlice</h2>
            <h4>Login</h4>
        </header>
        <form class="login-form" action="#" method="post">
            <input type="text" class="login-input" placeholder="Nombre" name="Nombre_cliente" required autofocus />
            <input type="text" class="login-input" placeholder="Direccion" name="Direccion" required />
            <input type="text" class="login-input" placeholder="Telefono" name="Telefono" required />
            <input type="text" class="login-input" placeholder="Email" name="Email" required />
            <input type="text" class="login-input" placeholder="Contraseña" name="Password" required />
            <div class="submit-container">
                <button type="submit" class="login-button">Registrarse</button>
            </div>
        </form>
    </section>
</div>
@section Style{
    <link rel="stylesheet" href="~/css/LoginStyle.css" />
}
@section Scripts {
    <script>
        var form = document.getElementById('login');
        var buttonE1 = document.getElementById('e1');

        buttonE1.addEventListener('click', function () {
            form.classList.add('error_1');
            setTimeout(function () {
                form.classList.remove('error_1');
            }, 3000);
        });
    </script>
}

ExtraSliceV2/Views/Carta/Restaurante.cshtml
@inject IMemoryCache memoryCache;
@using Microsoft.Extensions.Caching.Memory;
@model RestauranteProductos
@section Style{
    <link rel="stylesheet" href="~/css/RestauranteStyle.css" />
}
@{
    List<int> idsProductos = Context.Session.GetObject<List<int>>("IdProductos");
    List<Producto> favoritos = memoryCache.Get<List<Producto>>("FAVORITOS");
}



@if (Model != null)
{
    <div class="fondoRestaurante">
        <img src="@Model.Restaurante.Imagen" />
        <div class="datosRestaurante">
            <section class="restaurante">
                <h1>@Model.Restaurante.Nombre_restaurante</h1>
                <h2>@Model.Restaurante.Direccion</h2>
                <h3>Telefono: @Model.Restaurante.Telefono</h3>
            </section>
        </div>
    </div>


    <div id="menu" class="menu">
        @foreach (Producto pro in Model.Productos)
        {
            <div class="alimento">
                <h2>@pro.Nombre_producto</h2>
                <h3>@pro.Descripcion</h3>
                <h2>@pro.Precio €</h2>

                @* <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="@pro.IdRestaurante" asp-route-idfavorito="@pro.IdProducto">Añadir a Favoritos</a>*@
                <button class="add-to-favorites" data-restaurante-id="@pro.IdRestaurante" data-is-favorite="@pro.IdProducto"></button>

                @if (idsProductos == null)
                {
                    @* <button class="miBoton" value="@pro.IdProducto">Añadir Producto</button>*@
                    @* <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="@pro.IdRestaurante" asp-route-idproducto="@pro.IdProducto">Añadir al carrito</a>*@
                    <button data-restaurante-id="@pro.IdRestaurante" data-is-idproducto="@pro.IdProducto" onclick="addItem()" class="add-shop my-button but">Añadir a la cesta</button>
                    <img src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/si.png" class="my-image" style="width:40px; height: 40px;display:none" />
                }
                else
                {
                    if (idsProductos.Contains(pro.IdProducto))
                    {
                        <img src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/si.png" style="width:40px; height: 40px" />
                    }
                    else
                    {
                        @*<button class="miBoton" value="@pro.IdProducto">Añadir Producto</button>*@
                        @* <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="@pro.IdRestaurante" asp-route-idproducto="@pro.IdProducto">Añadir al carrito</a>*@
                       <button data-restaurante-id="@pro.IdRestaurante" data-is-idproducto="@pro.IdProducto" onclick="addItem()" class="add-shop my-button but">Añadir a la cesta</button>
                        <img src="https://storageextraslice.blob.core.windows.net/extrasliceblobs/si.png" class="my-image" style="width:40px; height: 40px;display:none" />
                    }

                }

            </div>

        }
    </div>
}
@section Scripts{

    <script>
        const cartItems = document.querySelector('.cart-items');

        let count = 0;

        function addItem() {
            count++;
            //cartItems.innerText = count;

            const newItem = document.createElement('div');
            newItem.classList.add('cart-items');
            newItem.innerText = '';

            const cart = document.querySelector('.cart');
            cart.appendChild(newItem);
        }


        $(document).ready(function () {

            $(".my-button").click(function () {
                console.log("pata")
                $(this).hide();
                $(this).next(".my-image").show();
            });

            $(".add-shop").click(function () {
                console.log("hola")
                var button = $(this);
                var restauranteId = button.data("restaurante-id");
                var isidproducto = button.data("is-idproducto");
                $.get("/Carta/SeleccionarProducto", { idrestaurante: restauranteId, idproducto: isidproducto });
                // Agregar o eliminar una clase CSS para cambiar el color del ícono

            });
            // Agregar el ícono de la estrella al botón
            $(".add-to-favorites").prepend('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 21.35l-1.8-1.64C4.74 14.21 2 10.8 2 7.5 2 4.42 4.42 2 7.5 2c2.34 0 4.47 1.43 5.5 3.63C12.03 3.43 14.16 2 16.5 2 19.58 2 22 4.42 22 7.5c0 3.31-2.74 6.71-8.2 12.21L12 21.35z"/></svg>');

            // Agregar un controlador de eventos para el botón
            $(".add-to-favorites").click(function () {
                var button = $(this);
                var restauranteId = button.data("restaurante-id");
                var isFavorite = button.data("is-favorite");
                $.get("/Carta/SeleccionarFavorito", { idrestaurante: restauranteId, idfavorito: isFavorite });
                // Agregar o eliminar una clase CSS para cambiar el color del ícono
                $(this).toggleClass("favorited");
            });


        });

    </script>
  }

ExtraSliceV2/Views/Carta/_ResaturanteOnCategoria.cshtml
@model List<Restaurante>

@if (Model != null)
{
    @foreach (Restaurante rest in Model)
    {
        <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="@rest.IdRestaurante" class="card grow">
            <img src="@rest.Imagen" />
            <div class="content">
                <h3>@rest.Nombre_restaurante</h3>
                <p>@rest.Direccion</p>
            </div>
        </a>
    }

}

ExtraSliceV2/Views/Carta/_RestaurantesByDinero.cshtml
@model List<Restaurante>

@if (Model != null)
{
    @foreach (Restaurante rest in Model)
    {
                <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="@rest.IdRestaurante" class="card grow">
                    <img src="@rest.Imagen" />
                    <div class="content">
                        <h3>@rest.Nombre_restaurante</h3>
                        <p>@rest.Direccion</p>
                    </div>
                </a>
    }

}

ExtraSliceV2/Views/Carta/_RestaurantesPartial.cshtml
@model List<Restaurante>

@if (Model != null)
{
    @foreach (Restaurante rest in Model)
    {
        <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="@rest.IdRestaurante" class="card grow" >
            <img src="@rest.Imagen" />
            <div class="content">
                <h3>@rest.Nombre_restaurante</h3>
                <p>@rest.Direccion</p>
            </div>
        </a>
    }

}

ExtraSliceV2/Views/Carta/_ShowRestauranteByName.cshtml
@model Restaurante

@if (Model != null)
{


    <a asp-controller="Carta" asp-action="Restaurante" asp-route-idrestaurante="@Model.IdRestaurante" class="card grow">
        <img src="@Model.Imagen" />
        <div class="content">
            <h3>@Model.Nombre_restaurante</h3>
            <p>@Model.Direccion</p>
        </div>
    </a>


}